### ISSUE TITLE
Needed to re-adding the armhf binary into repository or write build instruction of armhf

### ISSUE THREAD

**Issue by 00shadows** [ungoogled-software/ungoogled-chromium-debian#315]
Hello, to be clear there was still many people using armhf (mostly SBC's or chromebooks) we need ungoogled-chromium for armhf build to the repo's if someone did not doing that are anyone in here can adding build instruction for armhf? Let ungoogled-chromium build by my self

**Comment by 00shadows** [comment]
I have followed the 32bit patch base on [debian patches](https://launchpad.net/debian/+source/chromium/103.0.5060.53-1) but I still have error specially on ByteSwapUintPtrT

```
In file included from ../../base/allocator/partition_allocator/partition_root.cc:5:
In file included from ../../base/allocator/partition_allocator/partition_root.h:54:
In file included from ../../base/allocator/partition_allocator/partition_direct_map_extent.h:10:
In file included from ../../base/allocator/partition_allocator/partition_page.h:22:
../../base/allocator/partition_allocator/partition_freelist_entry.h:73:29: error: no member named 'ByteSwapUintPtrT' in namespace 'partition_alloc::internal::base'; did you mean '::base::ByteSwapUintPtrT'?
    uintptr_t transformed = base::ByteSwapUintPtrT(address);
                            ^~~~~~~~~~~~~~~~~~~~~~
                            ::base::ByteSwapUintPtrT                                  
../../base/allocator/partition_allocator/partition_alloc_base/sys_byteorder.h:54:28: note: '::base::ByteSwapUintPtrT' declared here                                         
inline constexpr uintptr_t ByteSwapUintPtrT(uintptr_t x) {
                           ^
1 error generated.                                                                    
ninja: build stopped: subcommand failed.
make[1]: *** [debian/rules:144: override_dh_auto_build] Error 1
```

**Comment by 00shadows** [comment]
I have this error when try to building on armhf as shown as below

```
FAILED: gen/media/mojo/mojom/stable/stable_video_decoder.mojom-module gen/media/mojo/mojom/stable/stable_video_decoder_types.mojom-module 
python3 ../../mojo/public/tools/mojom/mojom_parser.py --input-root ../.. --input-root gen --output-root gen --mojom-file-list=__media_mojo_mojom_stable_stable_video_decoder__parser___build_toolchain_linux_unbundle_default__rule..rsp --check-imports gen/media/mojo/mojom/stable/stable_video_decoder.build_metadata --enable-feature is_posix --enable-feature is_linux
Traceback (most recent call last):
  File "/mnt/ungoogled-chromium-debian/out/Release/../../mojo/public/tools/mojom/mojom_parser.py", line 496, in <module>
    Run(sys.argv[1:])
  File "/mnt/ungoogled-chromium-debian/out/Release/../../mojo/public/tools/mojom/mojom_parser.py", line 490, in Run
    _ParseMojoms(mojom_files, input_roots, output_root, module_roots,
  File "/mnt/ungoogled-chromium-debian/out/Release/../../mojo/public/tools/mojom/mojom_parser.py", line 330, in _ParseMojoms
    module_abspath = _ResolveRelativeImportPath(
  File "/mnt/ungoogled-chromium-debian/out/Release/../../mojo/public/tools/mojom/mojom_parser.py", line 61, in _ResolveRelativeImportPath
    raise ValueError('"%s" does not exist in any of %s' % (path, roots))
ValueError: "mojo/public/mojom/base/unguessable_token.mojom-module" does not exist in any of ['/mnt/ungoogled-chromium-debian/out/Release/gen']
ninja: build stopped: subcommand failed.

```

**Comment by ghost** [comment]
OBS support for armv7l (armhf) is back. But will still be awhile before new builds are available.

**Comment by 00shadows** [comment]
As seen on [ungoogled-chromium Official Repo](http://download.opensuse.org/repositories/home:/ungoogled_chromium/) this build is not available for Debian Bullseye armhf. Dude I am still using old Orange Pi Lite which using 512MB ram and using Armbian Bullseye, please build for Debian Bullseye armhf.

**Comment by ghost** [comment]
No can do, Bullseye support was already dropped.
